# Generated by Django 5.1.4 on 2026-07-13 04:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(choices=[('CI', 'Cedula'), ('PASAPORTE', 'Pasaporte'), ('RUC', 'RUC')], max_length=20)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identificacion'], name='usuarios_pe_identif_6939b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('PROPIETARIO', 'Propietario')], default='PROPIETARIO', max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('correo_verificado', models.BooleanField(default=False)),
                ('correo_verificado_en', models.DateTimeField(blank=True, null=True)),
                ('onboarding_estado', models.CharField(choices=[('CORREO_PENDIENTE', 'Correo pendiente'), ('DATOS_INICIALES_PENDIENTES', 'Datos iniciales pendientes'), ('REVISION_PENDIENTE', 'Revision pendiente'), ('RECHAZADO', 'Rechazado'), ('CONFIGURACION_PENDIENTE', 'Configuracion pendiente'), ('ACTIVO', 'Activo'), ('DESHABILITADO', 'Deshabilitado')], default='CORREO_PENDIENTE', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='usuarios.persona')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VerificacionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_correo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['rol'], name='usuarios_cu_rol_c7d0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['is_active'], name='usuarios_cu_is_acti_aa1f98_idx'),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['onboarding_estado'], name='usuarios_cu_onboard_dc0277_idx'),
        ),
        migrations.AddIndex(
            model_name='verificacioncorreo',
            index=models.Index(fields=['cuenta', 'expires_at'], name='usuarios_ve_cuenta__92cddc_idx'),
        ),
    ]
