# Generated by Django 5.1.4 on 2026-07-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_principal', models.CharField(max_length=200)),
                ('calle_secundaria', models.CharField(blank=True, max_length=200)),
                ('numero_lote', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('OCUPADO', 'Ocupado'), ('LIBRE', 'Libre'), ('INHABILITADO', 'Inhabilitado')], default='LIBRE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('habilitacion_estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('estado_operativo', models.CharField(choices=[('ABIERTO', 'Abierto'), ('LLENO', 'Lleno'), ('CERRADO', 'Cerrado'), ('INACTIVO', 'Inactivo'), ('FUERA_DE_SERVICIO', 'Fuera de servicio')], default='INACTIVO', max_length=30)),
                ('total_espacios', models.PositiveIntegerField(default=0)),
                ('espacios_disponibles', models.PositiveIntegerField(default=0)),
                ('configuracion_completa', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
