# Generated by Django 5.1.4 on 2026-07-13 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0001_initial'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='tarifa_predeterminada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='espacios_predeterminados', to='tarifas.categoriatarifa'),
        ),
    ]
