# Generated by Django 5.1 on 2026-06-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parqueaderos', to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='parqueadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='parqueaderos.parqueadero'),
        ),
        migrations.AddIndex(
            model_name='parqueadero',
            index=models.Index(fields=['nombre'], name='parqueadero_nombre_dd67ec_idx'),
        ),
        migrations.AddIndex(
            model_name='parqueadero',
            index=models.Index(fields=['aprobado'], name='parqueadero_aprobad_b997a5_idx'),
        ),
        migrations.AddIndex(
            model_name='parqueadero',
            index=models.Index(fields=['activo'], name='parqueadero_activo_7b8755_idx'),
        ),
        migrations.AddIndex(
            model_name='parqueadero',
            index=models.Index(fields=['latitud', 'longitud'], name='parqueadero_latitud_54d3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['estado'], name='parqueadero_estado_43b3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['parqueadero'], name='parqueadero_parquea_1538ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='espacio',
            unique_together={('parqueadero', 'codigo')},
        ),
    ]
