# Generated by Django 5.1.4 on 2026-07-13 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parqueadero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espacio',
            name='parqueadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='parqueaderos.parqueadero'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='parqueadero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='parqueaderos.parqueadero'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='parqueadero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='parqueaderos.parqueadero'),
        ),
        migrations.AddIndex(
            model_name='parqueadero',
            index=models.Index(fields=['nombre'], name='parqueadero_nombre_dd67ec_idx'),
        ),
        migrations.AddIndex(
            model_name='parqueadero',
            index=models.Index(fields=['habilitacion_estado', 'estado_operativo'], name='parqueadero_habilit_f21c0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='parqueadero',
            constraint=models.CheckConstraint(condition=models.Q(('espacios_disponibles__lte', models.F('total_espacios'))), name='park_available_lte_total'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['parqueadero', 'estado'], name='parqueadero_parquea_79ef1e_idx'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['parqueadero', 'is_active'], name='parqueadero_parquea_7f5025_idx'),
        ),
        migrations.AddConstraint(
            model_name='espacio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('parqueadero', 'nombre'), name='space_unique_active_name_per_park'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['latitud', 'longitud'], name='parqueadero_latitud_5b9d28_idx'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__gte', -90), ('latitud__lte', 90)), name='location_valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__gte', -180), ('longitud__lte', 180)), name='location_valid_longitude'),
        ),
    ]
