# Generated by Django 5.1.4 on 2026-07-13 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parqueadero',
            name='parqueadero_habilit_f21c0b_idx',
        ),
        migrations.AddIndex(
            model_name='parqueadero',
            index=models.Index(fields=['habilitacion_estado', 'configuracion_completa', 'estado_operativo'], name='parqueadero_habilit_45dd76_idx'),
        ),
    ]
