# Generated by Django 5.1.4 on 2026-07-13 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        ('parqueaderos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatencion',
            name='parqueadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='parqueaderos.parqueadero'),
        ),
        migrations.AddIndex(
            model_name='horarioatencion',
            index=models.Index(fields=['parqueadero', 'dia'], name='horarios_ho_parquea_34fb54_idx'),
        ),
        migrations.AddConstraint(
            model_name='horarioatencion',
            constraint=models.UniqueConstraint(fields=('parqueadero', 'dia'), name='schedule_unique_day_per_park'),
        ),
        migrations.AddConstraint(
            model_name='horarioatencion',
            constraint=models.CheckConstraint(condition=models.Q(('hora_apertura__lt', models.F('hora_cierre'))), name='schedule_open_before_close'),
        ),
    ]
