# Generated by Django 5.1.4 on 2026-07-13 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estancias', '0001_initial'),
        ('parqueaderos', '0001_initial'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estancia',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='parqueaderos.espacio'),
        ),
        migrations.AddField(
            model_name='estancia',
            name='tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='tarifas.categoriatarifa'),
        ),
        migrations.AddIndex(
            model_name='estancia',
            index=models.Index(fields=['espacio', 'estado'], name='estancias_e_espacio_31b2a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='estancia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('espacio',), name='stay_one_active_per_space'),
        ),
        migrations.AddConstraint(
            model_name='estancia',
            constraint=models.CheckConstraint(condition=models.Q(('precio_hora_snapshot__gte', 0)), name='stay_nonnegative_rate'),
        ),
        migrations.AddConstraint(
            model_name='estancia',
            constraint=models.CheckConstraint(condition=models.Q(('costo_total__isnull', True), ('costo_total__gte', 0), _connector='OR'), name='stay_nonnegative_total'),
        ),
    ]
