# Generated by Django 5.1.4 on 2026-07-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estancias', '0002_initial'),
        ('parqueaderos', '0003_initial'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estancia',
            index=models.Index(fields=['estado', 'fin'], name='estancias_e_estado_3d6854_idx'),
        ),
        migrations.AddConstraint(
            model_name='estancia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ACTIVA'), _negated=True), ('fin__isnull', True), _connector='OR'), name='stay_active_without_end'),
        ),
        migrations.AddConstraint(
            model_name='estancia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'FINALIZADA'), _negated=True), models.Q(('fin__isnull', False), ('minutos_reales__isnull', False), ('horas_cobradas__isnull', False), ('costo_total__isnull', False)), _connector='OR'), name='stay_finished_has_summary'),
        ),
    ]
