import React from 'react';
import { AlertCircle, CalendarClock, CarFront, CheckCircle2, CircleParking, CircleSlash2, Clock3, DollarSign, Gauge, MapPin, Power, Settings2, SquareParking } from 'lucide-react';
import { calcularOcupacion, etiquetaEstado, formatearMoneda, obtenerHorarioHoy, obtenerTarifa, pendientesConfiguracion, resumirEspacios } from '../../../utils/ownerDashboard';

const STATE_STYLE = { ABIERTO: 'bg-emerald-100 text-emerald-800', CERRADO: 'bg-rose-100 text-rose-800', LLENO: 'bg-amber-100 text-amber-900', FUERA_DE_SERVICIO: 'bg-slate-200 text-slate-800', INACTIVO: 'bg-slate-200 text-slate-800' };

const SummaryCard = ({ icon: Icon, title, value, detail, color, surface }) => <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`grid h-11 w-11 place-items-center rounded-xl ${surface} ${color}`}><Icon size={22} /></div><p className="mt-4 text-sm font-semibold text-slate-500">{title}</p><strong className="mt-1 block text-2xl font-black text-slate-900">{value}</strong><p className="mt-1 text-xs text-slate-500">{detail}</p></article>;

export const OwnerHome = ({ session, parqueadero, configuration, pending: statusPending, onChangeStatus, onNavigate }) => {
  const spaces = resumirEspacios(configuration?.espacios);
  const occupation = calcularOcupacion(spaces);
  const today = obtenerHorarioHoy(configuration?.horarios);
  const rates = { normal: obtenerTarifa(configuration?.tarifas, 'NORMAL'), discount: obtenerTarifa(configuration?.tarifas, 'DESCUENTO'), increment: obtenerTarifa(configuration?.tarifas, 'INCREMENTO') };
  const pending = pendientesConfiguracion(parqueadero, configuration);
  const ownerName = session?.persona?.nombre || 'Propietario';
  const updated = parqueadero?.updated_at ? new Intl.DateTimeFormat('es-EC', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(parqueadero.updated_at)) : null;
  const cards = [[SquareParking, 'Espacios totales', spaces.total, 'Espacios activos', 'text-sky-700', 'bg-sky-50'], [CircleParking, 'Disponibles', spaces.libres, 'Listos para recibir vehículos', 'text-emerald-700', 'bg-emerald-50'], [CarFront, 'Ocupados', spaces.ocupados, 'Con estancia activa', 'text-teal-700', 'bg-teal-50'], [CircleSlash2, 'Inhabilitados', spaces.inhabilitados, 'No disponibles', 'text-orange-700', 'bg-orange-50'], [DollarSign, 'Tarifa general', formatearMoneda(rates.normal?.precio_hora), 'Por hora', 'text-indigo-700', 'bg-indigo-50'], [Gauge, 'Estado operativo', etiquetaEstado(configuration?.estado_operativo), 'Calculado desde los espacios', 'text-violet-700', 'bg-violet-50']];

  return <div className="space-y-6 owner-view-enter">
    <section className="flex flex-col gap-5 rounded-3xl bg-gradient-to-r from-sky-700 to-blue-700 p-6 text-white shadow-lg sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-sky-100">Bienvenida, {ownerName}</p><h2 className="mt-2 text-2xl font-black">{parqueadero?.nombre || 'Tu parqueadero'}</h2><p className="mt-2 max-w-2xl text-sm text-sky-100">Aquí tienes el estado actual de tu operación y los accesos para mantenerla al día.</p>{updated && <p className="mt-3 flex items-center gap-2 text-xs text-sky-100"><Clock3 size={14} /> Última actualización: {updated}</p>}</div><span className={`self-start rounded-full px-4 py-2 text-xs font-black uppercase ${STATE_STYLE[configuration?.estado_operativo] || STATE_STYLE.INACTIVO}`}>{etiquetaEstado(configuration?.estado_operativo)}</span></section>
    <section className="flex flex-col gap-4 rounded-2xl border border-sky-200 bg-sky-50 p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between">
      <div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-sky-700 text-white"><Power aria-hidden="true" size={21} /></span><div><h3 className="font-black text-slate-950">Estado del parqueadero</h3><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">Selecciona Abierto, Cerrado o Fuera de servicio. Si está abierto y no quedan espacios libres, el sistema mostrará Lleno automáticamente.</p></div></div>
      <div className="w-full shrink-0 sm:w-64"><label htmlFor="owner-operational-status" className="mb-1.5 block text-xs font-bold text-slate-600">Cambiar estado</label><select id="owner-operational-status" value={configuration?.estado_operativo_manual || 'ABIERTO'} disabled={statusPending} onChange={(event) => onChangeStatus(event.target.value)} className="min-h-11 w-full rounded-xl border border-sky-300 bg-white px-3 text-sm font-bold text-slate-900 outline-none focus:border-sky-600 focus:ring-2 focus:ring-sky-200 disabled:cursor-wait disabled:opacity-60"><option value="ABIERTO">Abierto</option><option value="CERRADO">Cerrado</option><option value="FUERA_DE_SERVICIO">Fuera de servicio</option></select>{statusPending && <p className="mt-1.5 text-xs font-semibold text-sky-700" role="status">Actualizando estado…</p>}</div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([icon,title,value,detail,color,surface]) => <SummaryCard key={title} icon={icon} title={title} value={value} detail={detail} color={color} surface={surface} />)}</section>
    <div className="grid gap-6 xl:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Gauge className="text-sky-700" /><h3 className="text-lg font-black">Resumen de ocupación</h3></div><div className="mt-5 flex items-end justify-between"><strong className="text-4xl font-black">{occupation}%</strong><span className="text-sm text-slate-500">{spaces.libres} libres de {spaces.total}</span></div><div className="mt-4 flex h-4 overflow-hidden rounded-full bg-slate-100"><span style={{ width: `${spaces.total ? spaces.libres / spaces.total * 100 : 0}%`, backgroundColor: '#00bf63' }} /><span style={{ width: `${spaces.total ? spaces.ocupados / spaces.total * 100 : 0}%`, backgroundColor: '#0a878b' }} /><span style={{ width: `${spaces.total ? spaces.inhabilitados / spaces.total * 100 : 0}%`, backgroundColor: '#ff7c00' }} /></div><div className="mt-4 flex flex-wrap gap-4 text-xs font-semibold">{[['#00bf63','Libre'],['#0a878b','Ocupado'],['#ff7c00','Inhabilitado']].map(([color,label]) => <span className="flex items-center gap-2" key={label}><i className="h-3 w-3 rounded-full" style={{ backgroundColor: color }} />{label}</span>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><CalendarClock className="text-sky-700" /><h3 className="text-lg font-black">Horario de hoy</h3></div>{today ? <><p className="mt-6 text-2xl font-black">{today.hora_apertura.slice(0,5)} hasta {today.hora_cierre.slice(0,5)}</p><p className="mt-2 text-sm text-emerald-700">Atención configurada para hoy.</p></> : <><p className="mt-6 text-2xl font-black">Hoy no hay atención</p><p className="mt-2 text-sm text-slate-500">Este día no tiene un horario activo.</p></>}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><DollarSign className="text-sky-700" /><h3 className="text-lg font-black">Resumen de tarifas</h3></div><dl className="mt-5 space-y-3 text-sm">{[['General',rates.normal],['Preferencial / descuento',rates.discount],['Vehículos grandes / incremento',rates.increment]].map(([label,rate]) => <div className="flex justify-between gap-4 border-b border-slate-100 pb-3" key={label}><dt className="text-slate-500">{label}</dt><dd className="font-black">{formatearMoneda(rate?.precio_hora)}</dd></div>)}</dl></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3">{pending.length ? <AlertCircle className="text-amber-600" /> : <CheckCircle2 className="text-emerald-600" />}<h3 className="text-lg font-black">Estado de configuración</h3></div><p className="mt-4 font-bold">{pending.length ? 'Hay información pendiente' : 'Configuración completa'}</p>{pending.length > 0 && <ul className="mt-3 space-y-2 text-sm text-slate-600">{pending.map((item) => <li className="flex items-center justify-between gap-3" key={item.label}><span>• {item.label}</span><button className="font-bold text-sky-700" type="button" onClick={() => onNavigate(item.view)}>Completar</button></li>)}</ul>}</section>
    </div>
    <section className="rounded-2xl border border-slate-200 bg-slate-50 p-6"><h3 className="text-lg font-black">Acciones rápidas</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[MapPin,'Actualizar información','infoGeneral'],[CarFront,'Cambiar disponibilidad','configEspacios'],[Settings2,'Horarios y tarifas','configGeneral'],[SquareParking,'Gestionar espacios','configEspacios']].map(([Icon,label,view]) => <button className="flex min-h-14 items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 text-left font-bold shadow-sm transition hover:-translate-y-0.5 hover:border-sky-300" type="button" key={label} onClick={() => onNavigate(view)}><Icon className="text-sky-700" size={20} />{label}</button>)}</div></section>
  </div>;
};
