# Generated by Django 5.1 on 2026-06-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstrategiaTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parqueadero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa', to='parqueaderos.parqueadero')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motivo', models.CharField(max_length=100)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='tarifas.estrategiatarifa')),
            ],
        ),
        migrations.CreateModel(
            name='IncrementoTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motivo', models.CharField(max_length=100)),
                ('aplica_fin_semana', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incrementos', to='tarifas.estrategiatarifa')),
            ],
        ),
        migrations.AddIndex(
            model_name='estrategiatarifa',
            index=models.Index(fields=['tarifa_base'], name='tarifas_est_tarifa__5bce42_idx'),
        ),
    ]
