# Generated by Django 5.1.4 on 2026-07-13 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('NORMAL', 'Normal'), ('DESCUENTO', 'Descuento'), ('INCREMENTO', 'Incremento')], max_length=20)),
                ('nombre_visible', models.CharField(max_length=80)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='parqueaderos.parqueadero')),
            ],
            options={
                'indexes': [models.Index(fields=['parqueadero', 'activa'], name='tarifas_cat_parquea_8e69dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('parqueadero', 'codigo'), name='rate_unique_type_per_park'), models.CheckConstraint(condition=models.Q(('precio_hora__gte', 0)), name='rate_nonnegative_price')],
            },
        ),
    ]
