# Generated by Django 5.1.4 on 2026-07-13 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentohabilitacion',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_habilitacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentohabilitacion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentohabilitacion',
            index=models.Index(fields=['estado', 'uploaded_at'], name='documentos__estado_f12bef_idx'),
        ),
    ]
